services:
  # ========================================
  # 1. PostgreSQL Database
  # ========================================
  postgres:
    image: docker.io/postgres:18-alpine  # PostgreSQL 18
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"  # Bind apenas localhost (seguran√ßa)
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      N8N_DB_USER: ${N8N_DB_USER:-n8n}
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD:-n8n}
      N8N_DB_NAME: ${N8N_DB_NAME:-n8n}      
      N8N_WORKFLOWS_USER: ${N8N_WORKFLOWS_USER:-n8n_workflows}
      N8N_WORKFLOWS_PASSWORD: ${N8N_WORKFLOWS_PASSWORD:-n8n}
      N8N_WORKFLOWS_DB: ${N8N_WORKFLOWS_DB:-n8n_workflows}      
    volumes:
      #- ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - n8n_network
  # ========================================
  # 2. pgAdmin (Interface Web)
  # ========================================
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-seuemail@ponto.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-master}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - n8n_network      
  # ========================================
  # 3. N8N com banco postgresql
  # ========================================
  n8n:
    image: docker.io/n8nio/n8n:1.122.2
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_SECURE_COOKIE=false
    # Monta um volume persistente para armazenar dados como workflows e credenciais.
    volumes:
      - n8n_data:/home/node/.n8n   
    networks:
      - n8n_network      
    depends_on:
      postgres:
        condition: service_healthy      

volumes:
  n8n_data:
  postgres_data:
  pgadmin_data:

networks:
  n8n_network:
    driver: bridge 